export {
  listLossReasons,
  getLossReasonsByPipeline,
  getDisqualifyReasonsForPipeline,
  createLossReason,
  updateLossReason,
  deleteLossReason,
  toggleLossReasonStatus,
  seedPreSalesDisqualificationReasons,
  applyLossWinReasonsScopeMatrix,
  type LossReason,
  type LossReasonType,
  type LossReasonInput,
  type ScopeMatrixReport,
} from '../supabase/loss-reasons';
