// Re-export functions from Supabase service
export {
  sendProposal,
  getProposal,
  getProposalWithDetails,
  createProposal,
  updateProposal,
  deleteProposal,
  listProposals,
  generateProposalPDF,
  sendProposalEmail,
  duplicateProposal,
  createVersion,
  getProposalVersions,
  generatePublicToken,
  getProposalByToken,
  acceptProposal,
  declineProposal,
  reopenProposal,
  trackView,
  updateProposalView,
  getProposalStats,
  updateProposalTotals,
  syncOpportunityValue,
  searchProposalsGlobal,
  type SearchProposalsGlobalParams,
} from '../supabase/proposals';
