// Re-export functions from Supabase service
export {
  sendProposal,
  getProposal,
  createProposal,
  updateProposal,
  deleteProposal,
  listProposals,
  generateProposalPDF,
  sendProposalEmail,
  duplicateProposal,
  createVersion,
  getProposalVersions,
  generatePublicToken,
  getProposalByToken,
  acceptProposal,
  declineProposal,
  trackView,
  getProposalStats,
  updateProposalTotals,
} from '../supabase/proposals';
