// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL) {
  throw new Error('[AUTH_CONFIG_ERROR] Missing VITE_SUPABASE_URL');
}

if (!SUPABASE_ANON_KEY) {
  throw new Error('[AUTH_CONFIG_ERROR] Missing VITE_SUPABASE_ANON_KEY');
}

if (SUPABASE_ANON_KEY.toLowerCase().includes('service_role')) {
  throw new Error('[AUTH_CONFIG_ERROR] service_role key is not allowed in frontend auth client');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

export const supabaseClientSingleton = true;
